### ISSUE TITLE
Gulp error on fresh install

### ISSUE THREAD

**Issue by nigelwhite** [SimonMueller/grav-theme-pluspunkt#23]
$ cd user/themes/pluspunkt // not a sub-theme
$ npm install
$ npm audit fix
$ npm audit fix --force
$ gulp
`
[07:41:03] Failed to load external module @babel/register
[07:41:03] Requiring external module babel-register
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/pluspunkt/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/pluspunkt/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/pluspunkt/gulpfile.babel.js:25:6)
    at Module._compile (module.js:652:30)
    at loader (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/pluspunkt/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/pluspunkt/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
`

Grav 1.5.10

**Comment by SimonMueller** [comment]
Hi there

This is expected behaviour of using `npm audit fix --force`. This can change the e.g. the major version of a dependency as it does in this example with the package `gulp`. It updates gulp from version 3.9.0 to 4.0.0 which introduces breaking changes. If you use the --force flag it even outputs a warning. See the documentation for more information.
`npm audit fix` without the --force flag is safer.

In this case the output of  `npm audit` should not be a big issue because the main findings are from the dependency of gulp which is only the task runner used to build the assets. 

I hope this helps 😄

**Comment by nigelwhite** [comment]
Thank you
